@echo off
echo Creating all missing template files...

REM Create admin templates
echo Creating admin/recordings.html...
copy NUL templates\admin\recordings.html > NUL
echo Creating admin/register_student.html...
copy NUL templates\admin\register_student.html > NUL
echo Creating admin/verify_false_positives.html...
copy NUL templates\admin\verify_false_positives.html > NUL
echo Creating admin/settings.html...
copy NUL templates\admin\settings.html > NUL

REM Create teacher templates
echo Creating teacher/dashboard.html...
copy NUL templates\teacher\dashboard.html > NUL
echo Creating teacher/class_view.html...
copy NUL templates\teacher\class_view.html > NUL

REM Create parent templates
echo Creating parent/login.html...
copy NUL templates\parent\login.html > NUL
echo Creating parent/dashboard.html...
copy NUL templates\parent\dashboard.html > NUL

REM Create CSS and JS files
echo Creating static/css/style.css...
copy NUL static\css\style.css > NUL
echo Creating static/js/main.js...
copy NUL static\js\main.js > NUL

echo All template files created!
echo.
echo Now copy the content from the previous messages into each file.
pause